version: '3.8'
services:
  app:
    container_name: restaurantapp_api
    build: .
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - DB_PORT=.env
      - DB_HOST=.env
      - DB_USER=.env
      - DB_PASSWORD=.env
      - DB_NAME=.env