version: '3.8'
services:
  app:
    container_name: restaurantapp_api
    build: .
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - DB_PORT
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}